### PR TITLE
Upgrade rapidjson

### PR DESCRIPTION
**Pull request by antmat**
* upgrade rapidjson to newer version
  * allow comments and trailing commas in config
  * allow dynamic_t from reference wrapper construction
  * remove redundant, producing compilation warning on release build, assert

### CODE REVIEW

**Comment by 3Hren** [comment]
Show me `nm -gDC /usr/lib/libcocaine-core.so | grep rapidjson` on linux.

**Comment by antmat** [comment]
Yes, my lord!
```
000000000015f6f0 W void rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseArray<160u, rapidjson::BasicIStreamWrapper<std::istream>, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator> >(rapidjson::BasicIStreamWrapper<std::istream>&, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator>&)
000000000015f030 W void rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseValue<160u, rapidjson::BasicIStreamWrapper<std::istream>, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator> >(rapidjson::BasicIStreamWrapper<std::istream>&, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator>&)
000000000015de40 W void rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseNumber<160u, rapidjson::BasicIStreamWrapper<std::istream>, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator> >(rapidjson::BasicIStreamWrapper<std::istream>&, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator>&)
000000000015f3c0 W void rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseObject<160u, rapidjson::BasicIStreamWrapper<std::istream>, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator> >(rapidjson::BasicIStreamWrapper<std::istream>&, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator>&)
000000000015eca0 W void rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseString<160u, rapidjson::BasicIStreamWrapper<std::istream>, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator> >(rapidjson::BasicIStreamWrapper<std::istream>&, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator>&, bool)
000000000015d1b0 W void rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::SkipWhitespaceAndComments<160u, rapidjson::BasicIStreamWrapper<std::istream> >(rapidjson::BasicIStreamWrapper<std::istream>&)
000000000015dc20 W unsigned int rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseHex4<rapidjson::BasicIStreamWrapper<std::istream> >(rapidjson::BasicIStreamWrapper<std::istream>&, unsigned long)
000000000015d160 W void rapidjson::SkipWhitespace<rapidjson::BasicIStreamWrapper<std::istream> >(rapidjson::BasicIStreamWrapper<std::istream>&)
000000000015daf0 W rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator>::EndArray(unsigned int)
000000000015d9c0 W rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator>::EndObject(unsigned int)
000000000015c090 W rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator>::~GenericDocument()
000000000015c090 W rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator>::~GenericDocument()
000000000015b930 W rapidjson::GetParseError_En(rapidjson::ParseErrorCode)
000000000015dcc0 W rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>::Malloc(unsigned long)
000000000015eb30 W void rapidjson::UTF8<char>::Encode<rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::StackStream<char> >(rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::StackStream<char>&, unsigned int)
000000000015ea80 W void rapidjson::internal::Stack<rapidjson::CrtAllocator>::Expand<char>(unsigned long)
000000000015dd80 W void rapidjson::internal::Stack<rapidjson::CrtAllocator>::Expand<rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > >(unsigned long)
00000000001db8c0 u void rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseStringToStream<160u, rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::BasicIStreamWrapper<std::istream>, rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::StackStream<char> >(rapidjson::BasicIStreamWrapper<std::istream>&, rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::StackStream<char>&)::escape
00000000001daf00 u rapidjson::internal::Pow10(int)::e
```

**Comment by antmat** [comment]
fixed

**Comment by 3Hren** [comment]
LGBT.

**Comment by 3Hren** [comment]
WTF, commit style!

`git commit --amend -m "feat: allow comments and commas in config" && git push -f`

**Pull request merged**
